with countries as (
  select unnest(string_to_array('Indonesia,Bangladesh,Brunei Darussalam,Cameroon,Luxembourg,Czech Republic,Sweden,Viet Nam,Uganda,Montenegro,Jordan,Serbia and Montenegro,Syrian Arab Republic,Dominican Republic,Ireland,Cambodia,Singapore,Papua New Guinea,Sri Lanka,San Marino,Uzbekistan,Congo the Democratic Republic of the,Portugal,Moldova Republic of,Finland,Malta,Colombia,Venezuela Bolivarian Republic of,Albania,Ukraine,Saudi Arabia,Cayman Islands,Côte Divoire,Cuba,Latvia,Kyrgyzstan,Algeria,France,Réunion,Cape Verde,Slovakia,Maldives,Israel,Djibouti,Nauru,Senegal,Malaysia,Kenya,Ghana,Zambia,Iceland,Madagascar,Kuwait,Hong Kong,Sierra Leone,Liberia,Bosnia and Herzegovina,Philippines,Korea Republic of,Benin,Korea Democratic People Republic of,United States,Guinea,Cyprus,Turkey,Nigeria,Rwanda,Zimbabwe,Tajikistan,Guam,Comoros,China,Saint Lucia,New Caledonia,Belarus,Armenia,Qatar,Netherlands,Lesotho,Paraguay,Gabon,Martinique,Australia,Serbia,Mauritius,Angola,Libya,Vanuatu,Bahrain,Spain,Virgin Islands British,Congo,United Arab Emirates,Tanzania United Republic of,Saint Helena Ascension and Tristan da Cunha,Georgia,Malawi,Belgium,Guernsey,Bhutan,Solomon Islands,Macedonia the Former Yugoslav Republic of,Thailand,Togo,Burkina Faso,Faroe Islands,El Salvador,Italy,Antarctica,Uruguay,Oman,Fiji,United Kingdom,Palau,Germany,Eritrea,Canada,Barbados,Svalbard and Jan Mayen,Saint Vincent and the Grenadines,Bermuda,Namibia,Argentina,Taiwan Province of China,Liechtenstein,Slovenia,Azerbaijan,Greece,Egypt,Bahamas,Afghanistan,Puerto Rico,India,Chad,Timor-Leste,Saint Kitts and Nevis,French Polynesia,Chile,Gambia,Estonia,Virgin Islands U.S.,Suriname,South Africa,Peru,Isle of Man,Kazakhstan,Central African Republic,Guadeloupe,Japan,Macao,Iran Islamic Republic of,Denmark,Jamaica,Trinidad and Tobago,Mongolia,Bolivia Plurinational State of,Iraq,Mauritania,Mozambique,Switzerland,Northern Mariana Islands,New Zealand,Ecuador,Hungary,Norway,Honduras,Belize,Botswana,Russian Federation,Pakistan,Romania,Brazil,Austria,Guatemala,Guinea-Bissau,Ethiopia,Niger,Panama,Yemen,South Sudan,Lithuania,Bulgaria,Turkmenistan,Croatia,Tunisia,Sudan,Aruba,Mali,Lao People Democratic Republic,Swaziland,Morocco,Myanmar,British Indian Ocean Territory,Nicaragua,Mexico,French Southern Territories,Nepal,Guyana,Curaçao,Poland,Lebanon,Greenland,Costa Rica,Haiti,Gibraltar,Samoa,Equatorial Guinea,Palestine State of,Antigua and Barbuda,Somalia,Andorra', ',')) as country
)
select
  s.time,
  round(hll_cardinality(hll_union_agg(s."Kubernetes"))) as "Kubernetes",
  round(hll_cardinality(hll_union_agg(s."Istio"))) as "Istio",
  round(hll_cardinality(hll_union_agg(s."OpenTelemetry"))) as "OpenTelemetry",
  round(hll_cardinality(hll_union_agg(s."Knative"))) as "Knative",
  round(hll_cardinality(hll_union_agg(s."KubeVirt"))) as "KubeVirt",
  round(hll_cardinality(hll_union_agg(s."gRPC"))) as "gRPC",
  round(hll_cardinality(hll_union_agg(s."Envoy"))) as "Envoy",
  round(hll_cardinality(hll_union_agg(s."Helm"))) as "Helm",
  round(hll_cardinality(hll_union_agg(s."Cilium"))) as "Cilium",
  round(hll_cardinality(hll_union_agg(s."Argo"))) as "Argo",
  round(hll_cardinality(hll_union_agg(s."Prometheus"))) as "Prometheus",
  round(hll_cardinality(hll_union_agg(s."TiKV"))) as "TiKV",
  round(hll_cardinality(hll_union_agg(s."Kubeflow"))) as "Kubeflow",
  round(hll_cardinality(hll_union_agg(s."Backstage"))) as "Backstage",
  round(hll_cardinality(hll_union_agg(s."Operator Framework"))) as "Operator Framework",
  round(hll_cardinality(hll_union_agg(s."CNCF"))) as "CNCF",
  round(hll_cardinality(hll_union_agg(s."Keycloak"))) as "Keycloak",
  round(hll_cardinality(hll_union_agg(s."CRI-O"))) as "CRI-O",
  round(hll_cardinality(hll_union_agg(s."Network Service Mesh"))) as "Network Service Mesh",
  round(hll_cardinality(hll_union_agg(s."NATS"))) as "NATS",
  round(hll_cardinality(hll_union_agg(s."containerd"))) as "containerd",
  round(hll_cardinality(hll_union_agg(s."Dapr"))) as "Dapr",
  round(hll_cardinality(hll_union_agg(s."etcd"))) as "etcd",
  round(hll_cardinality(hll_union_agg(s."Linkerd"))) as "Linkerd",
  round(hll_cardinality(hll_union_agg(s."OpenEBS"))) as "OpenEBS",
  round(hll_cardinality(hll_union_agg(s."Harbor"))) as "Harbor",
  round(hll_cardinality(hll_union_agg(s."Fluentd"))) as "Fluentd",
  round(hll_cardinality(hll_union_agg(s."Vitess"))) as "Vitess",
  round(hll_cardinality(hll_union_agg(s."cdk8s"))) as "cdk8s",
  round(hll_cardinality(hll_union_agg(s."Falco"))) as "Falco",
  round(hll_cardinality(hll_union_agg(s."Keptn"))) as "Keptn",
  round(hll_cardinality(hll_union_agg(s."Rook"))) as "Rook",
  round(hll_cardinality(hll_union_agg(s."Meshery"))) as "Meshery",
  round(hll_cardinality(hll_union_agg(s."Longhorn"))) as "Longhorn",
  round(hll_cardinality(hll_union_agg(s."Flux"))) as "Flux",
  round(hll_cardinality(hll_union_agg(s."Jaeger"))) as "Jaeger",
  round(hll_cardinality(hll_union_agg(s."Strimzi"))) as "Strimzi",
  round(hll_cardinality(hll_union_agg(s."Submariner"))) as "Submariner",
  round(hll_cardinality(hll_union_agg(s."Antrea"))) as "Antrea",
  round(hll_cardinality(hll_union_agg(s."cert-manager"))) as "cert-manager",
  round(hll_cardinality(hll_union_agg(s."Kyverno"))) as "Kyverno",
  round(hll_cardinality(hll_union_agg(s."metal3-io"))) as "metal3-io",
  round(hll_cardinality(hll_union_agg(s."Buildpacks"))) as "Buildpacks",
  round(hll_cardinality(hll_union_agg(s."OpenFeature"))) as "OpenFeature",
  round(hll_cardinality(hll_union_agg(s."Open Policy Agent"))) as "Open Policy Agent",
  round(hll_cardinality(hll_union_agg(s."Kuma"))) as "Kuma",
  round(hll_cardinality(hll_union_agg(s."Crossplane"))) as "Crossplane",
  round(hll_cardinality(hll_union_agg(s."Konveyor"))) as "Konveyor",
  round(hll_cardinality(hll_union_agg(s."K3s"))) as "K3s",
  round(hll_cardinality(hll_union_agg(s."KubeEdge"))) as "KubeEdge",
  round(hll_cardinality(hll_union_agg(s."Atlantis"))) as "Atlantis",
  round(hll_cardinality(hll_union_agg(s."Thanos"))) as "Thanos",
  round(hll_cardinality(hll_union_agg(s."Dragonfly"))) as "Dragonfly",
  round(hll_cardinality(hll_union_agg(s."Karmada"))) as "Karmada",
  round(hll_cardinality(hll_union_agg(s."KEDA"))) as "KEDA",
  round(hll_cardinality(hll_union_agg(s."CoreDNS"))) as "CoreDNS",
  round(hll_cardinality(hll_union_agg(s."LitmusChaos"))) as "LitmusChaos",
  round(hll_cardinality(hll_union_agg(s."Pravega"))) as "Pravega",
  round(hll_cardinality(hll_union_agg(s."GraphQL"))) as "GraphQL",
  round(hll_cardinality(hll_union_agg(s."Flatcar"))) as "Flatcar",
  round(hll_cardinality(hll_union_agg(s."KubeVela"))) as "KubeVela",
  round(hll_cardinality(hll_union_agg(s."Chaos Mesh"))) as "Chaos Mesh",
  round(hll_cardinality(hll_union_agg(s."Cortex"))) as "Cortex",
  round(hll_cardinality(hll_union_agg(s."Kairos"))) as "Kairos",
  round(hll_cardinality(hll_union_agg(s."Contour"))) as "Contour",
  round(hll_cardinality(hll_union_agg(s."wasmCloud"))) as "wasmCloud",
  round(hll_cardinality(hll_union_agg(s."kubewarden"))) as "kubewarden",
  round(hll_cardinality(hll_union_agg(s."PipeCD"))) as "PipeCD",
  round(hll_cardinality(hll_union_agg(s."kpt"))) as "kpt",
  round(hll_cardinality(hll_union_agg(s."OpenFGA"))) as "OpenFGA",
  round(hll_cardinality(hll_union_agg(s."Open Cluster Management"))) as "Open Cluster Management",
  round(hll_cardinality(hll_union_agg(s."kcp"))) as "kcp",
  round(hll_cardinality(hll_union_agg(s."Carvel"))) as "Carvel",
  round(hll_cardinality(hll_union_agg(s."werf"))) as "werf",
  round(hll_cardinality(hll_union_agg(s."SPIRE"))) as "SPIRE",
  round(hll_cardinality(hll_union_agg(s."Notary"))) as "Notary",
  round(hll_cardinality(hll_union_agg(s."Confidential Containers"))) as "Confidential Containers",
  round(hll_cardinality(hll_union_agg(s."CloudEvents"))) as "CloudEvents",
  round(hll_cardinality(hll_union_agg(s."Volcano"))) as "Volcano",
  round(hll_cardinality(hll_union_agg(s."Kubescape"))) as "Kubescape",
  round(hll_cardinality(hll_union_agg(s."Tremor"))) as "Tremor",
  round(hll_cardinality(hll_union_agg(s."Spiderpool"))) as "Spiderpool",
  round(hll_cardinality(hll_union_agg(s."Inspektor Gadget"))) as "Inspektor Gadget",
  round(hll_cardinality(hll_union_agg(s."WasmEdge Runtime"))) as "WasmEdge Runtime",
  round(hll_cardinality(hll_union_agg(s."External Secrets Operator"))) as "External Secrets Operator",
  round(hll_cardinality(hll_union_agg(s."Distribution"))) as "Distribution",
  round(hll_cardinality(hll_union_agg(s."Devfile"))) as "Devfile",
  round(hll_cardinality(hll_union_agg(s."Open Service Mesh"))) as "Open Service Mesh",
  round(hll_cardinality(hll_union_agg(s."Kuadrant"))) as "Kuadrant",
  round(hll_cardinality(hll_union_agg(s."Emissary-ingress"))) as "Emissary-ingress",
  round(hll_cardinality(hll_union_agg(s."TUF"))) as "TUF",
  round(hll_cardinality(hll_union_agg(s."Curve"))) as "Curve",
  round(hll_cardinality(hll_union_agg(s."ORAS"))) as "ORAS",
  round(hll_cardinality(hll_union_agg(s."Cloud Custodian"))) as "Cloud Custodian",
  round(hll_cardinality(hll_union_agg(s."Bank-Vaults"))) as "Bank-Vaults",
  round(hll_cardinality(hll_union_agg(s."MetalLB"))) as "MetalLB",
  round(hll_cardinality(hll_union_agg(s."Tinkerbell"))) as "Tinkerbell",
  round(hll_cardinality(hll_union_agg(s."Telepresence"))) as "Telepresence",
  round(hll_cardinality(hll_union_agg(s."rkt"))) as "rkt",
  round(hll_cardinality(hll_union_agg(s."Kube-OVN"))) as "Kube-OVN",
  round(hll_cardinality(hll_union_agg(s."Kubestellar"))) as "Kubestellar",
  round(hll_cardinality(hll_union_agg(s."Kanister"))) as "Kanister",
  round(hll_cardinality(hll_union_agg(s."Fluid"))) as "Fluid",
  round(hll_cardinality(hll_union_agg(s."Dex"))) as "Dex",
  round(hll_cardinality(hll_union_agg(s."OpenYurt"))) as "OpenYurt",
  round(hll_cardinality(hll_union_agg(s."OpenKruise"))) as "OpenKruise",
  round(hll_cardinality(hll_union_agg(s."CubeFS"))) as "CubeFS",
  round(hll_cardinality(hll_union_agg(s."Lima"))) as "Lima",
  round(hll_cardinality(hll_union_agg(s."SPIFFE"))) as "SPIFFE",
  round(hll_cardinality(hll_union_agg(s."easegress"))) as "easegress",
  round(hll_cardinality(hll_union_agg(s."in-toto"))) as "in-toto",
  round(hll_cardinality(hll_union_agg(s."Brigade"))) as "Brigade",
  round(hll_cardinality(hll_union_agg(s."Connect RPC"))) as "Connect RPC",
  round(hll_cardinality(hll_union_agg(s."Armada"))) as "Armada",
  round(hll_cardinality(hll_union_agg(s."Porter"))) as "Porter",
  round(hll_cardinality(hll_union_agg(s."Radius"))) as "Radius",
  round(hll_cardinality(hll_union_agg(s."KubeArmor"))) as "KubeArmor",
  round(hll_cardinality(hll_union_agg(s."Shipwright"))) as "Shipwright",
  round(hll_cardinality(hll_union_agg(s."Koordinator"))) as "Koordinator",
  round(hll_cardinality(hll_union_agg(s."Pixie"))) as "Pixie",
  round(hll_cardinality(hll_union_agg(s."Kudo"))) as "Kudo",
  round(hll_cardinality(hll_union_agg(s."CNI"))) as "CNI",
  round(hll_cardinality(hll_union_agg(s."Kepler"))) as "Kepler",
  round(hll_cardinality(hll_union_agg(s."Keylime"))) as "Keylime",
  round(hll_cardinality(hll_union_agg(s."Perses"))) as "Perses",
  round(hll_cardinality(hll_union_agg(s."SOPS"))) as "SOPS",
  round(hll_cardinality(hll_union_agg(s."Athenz"))) as "Athenz",
  round(hll_cardinality(hll_union_agg(s."Headlamp"))) as "Headlamp",
  round(hll_cardinality(hll_union_agg(s."zot"))) as "zot",
  round(hll_cardinality(hll_union_agg(s."Artifact Hub"))) as "Artifact Hub",
  round(hll_cardinality(hll_union_agg(s."K8sGPT"))) as "K8sGPT",
  round(hll_cardinality(hll_union_agg(s."PARSEC"))) as "PARSEC",
  round(hll_cardinality(hll_union_agg(s."SlimToolkit"))) as "SlimToolkit",
  round(hll_cardinality(hll_union_agg(s."KCL"))) as "KCL",
  round(hll_cardinality(hll_union_agg(s."ContainerSSH"))) as "ContainerSSH",
  round(hll_cardinality(hll_union_agg(s."kube-rs"))) as "kube-rs",
  round(hll_cardinality(hll_union_agg(s."Virtual Kubelet"))) as "Virtual Kubelet",
  round(hll_cardinality(hll_union_agg(s."K8GB"))) as "K8GB",
  round(hll_cardinality(hll_union_agg(s."Serverless Workflow"))) as "Serverless Workflow",
  round(hll_cardinality(hll_union_agg(s."DevSpace"))) as "DevSpace",
  round(hll_cardinality(hll_union_agg(s."Nocalhost"))) as "Nocalhost",
  round(hll_cardinality(hll_union_agg(s."Logging Operator"))) as "Logging Operator",
  round(hll_cardinality(hll_union_agg(s."CNCF TOC"))) as "CNCF TOC",
  round(hll_cardinality(hll_union_agg(s."ChaosBlade"))) as "ChaosBlade",
  round(hll_cardinality(hll_union_agg(s."K8up"))) as "K8up",
  round(hll_cardinality(hll_union_agg(s."ko"))) as "ko",
  round(hll_cardinality(hll_union_agg(s."Microcks"))) as "Microcks",
  round(hll_cardinality(hll_union_agg(s."DevStream"))) as "DevStream",
  round(hll_cardinality(hll_union_agg(s."OpenCost"))) as "OpenCost",
  round(hll_cardinality(hll_union_agg(s."Score"))) as "Score",
  round(hll_cardinality(hll_union_agg(s."sealer"))) as "sealer",
  round(hll_cardinality(hll_union_agg(s."Cartography"))) as "Cartography",
  round(hll_cardinality(hll_union_agg(s."Xline"))) as "Xline",
  round(hll_cardinality(hll_union_agg(s."Ratify"))) as "Ratify",
  round(hll_cardinality(hll_union_agg(s."Kubeslice"))) as "Kubeslice",
  round(hll_cardinality(hll_union_agg(s."TrestleGRC"))) as "TrestleGRC",
  round(hll_cardinality(hll_union_agg(s."OpenFunction"))) as "OpenFunction",
  round(hll_cardinality(hll_union_agg(s."Vineyard"))) as "Vineyard",
  round(hll_cardinality(hll_union_agg(s."Curiefense"))) as "Curiefense",
  round(hll_cardinality(hll_union_agg(s."BFE"))) as "BFE",
  round(hll_cardinality(hll_union_agg(s."Capsule"))) as "Capsule",
  round(hll_cardinality(hll_union_agg(s."bpfman"))) as "bpfman",
  round(hll_cardinality(hll_union_agg(s."Serverless Devs"))) as "Serverless Devs",
  round(hll_cardinality(hll_union_agg(s."Inclavare Containers"))) as "Inclavare Containers",
  round(hll_cardinality(hll_union_agg(s."OpenGitOps"))) as "OpenGitOps",
  round(hll_cardinality(hll_union_agg(s."Kuberhealthy"))) as "Kuberhealthy",
  round(hll_cardinality(hll_union_agg(s."Kured"))) as "Kured",
  round(hll_cardinality(hll_union_agg(s."Hwameistor"))) as "Hwameistor",
  round(hll_cardinality(hll_union_agg(s."Piraeus-Datastore"))) as "Piraeus-Datastore",
  round(hll_cardinality(hll_union_agg(s."Kubeclipper"))) as "Kubeclipper",
  round(hll_cardinality(hll_union_agg(s."openGemini"))) as "openGemini",
  round(hll_cardinality(hll_union_agg(s."Akri"))) as "Akri",
  round(hll_cardinality(hll_union_agg(s."Kubean"))) as "Kubean",
  round(hll_cardinality(hll_union_agg(s."Krustlet"))) as "Krustlet",
  round(hll_cardinality(hll_union_agg(s."VS Code Kubernetes Tools"))) as "VS Code Kubernetes Tools",
  round(hll_cardinality(hll_union_agg(s."kube-vip"))) as "kube-vip",
  round(hll_cardinality(hll_union_agg(s."Eraser"))) as "Eraser",
  round(hll_cardinality(hll_union_agg(s."SchemaHero"))) as "SchemaHero",
  round(hll_cardinality(hll_union_agg(s."Paralus"))) as "Paralus",
  round(hll_cardinality(hll_union_agg(s."LoxiLB"))) as "LoxiLB",
  round(hll_cardinality(hll_union_agg(s."krkn"))) as "krkn",
  round(hll_cardinality(hll_union_agg(s."Clusternet"))) as "Clusternet",
  round(hll_cardinality(hll_union_agg(s."Copa"))) as "Copa",
  round(hll_cardinality(hll_union_agg(s."Clusterpedia"))) as "Clusterpedia",
  round(hll_cardinality(hll_union_agg(s."kube-burner"))) as "kube-burner",
  round(hll_cardinality(hll_union_agg(s."Trickster"))) as "Trickster",
  round(hll_cardinality(hll_union_agg(s."Service Mesh Performance"))) as "Service Mesh Performance",
  round(hll_cardinality(hll_union_agg(s."Stacker"))) as "Stacker",
  round(hll_cardinality(hll_union_agg(s."Foniod"))) as "Foniod",
  round(hll_cardinality(hll_union_agg(s."Aeraki Mesh"))) as "Aeraki Mesh",
  round(hll_cardinality(hll_union_agg(s."SMI"))) as "SMI",
  round(hll_cardinality(hll_union_agg(s."Teller"))) as "Teller",
  round(hll_cardinality(hll_union_agg(s."SuperEdge"))) as "SuperEdge",
  round(hll_cardinality(hll_union_agg(s."OpenELB"))) as "OpenELB",
  round(hll_cardinality(hll_union_agg(s."Merbridge"))) as "Merbridge",
  round(hll_cardinality(hll_union_agg(s."Skooner"))) as "Skooner",
  round(hll_cardinality(hll_union_agg(s."KubeDL"))) as "KubeDL",
  round(hll_cardinality(hll_union_agg(s."HAMi"))) as "HAMi",
  round(hll_cardinality(hll_union_agg(s."keycloak"))) as "keycloak",
  round(hll_cardinality(hll_union_agg(s."FabEdge"))) as "FabEdge",
  round(hll_cardinality(hll_union_agg(s."Kuasar"))) as "Kuasar",
  round(hll_cardinality(hll_union_agg(s."Hexa"))) as "Hexa",
  round(hll_cardinality(hll_union_agg(s."OPCR"))) as "OPCR",
  round(hll_cardinality(hll_union_agg(s."Carina"))) as "Carina",
  round(hll_cardinality(hll_union_agg(s."CNI-Genie"))) as "CNI-Genie",
  round(hll_cardinality(hll_union_agg(s."Krator"))) as "Krator"
from
  sprjcntr s,
  countries c
where
  s.time BETWEEN '2014-09-28T13:58:13.72Z' AND '2024-09-28T13:58:13.72Z'
  and s.period = 'q'
  and s.series = 'prjcntr' || c.country || 'contributions'
group by
  s.time
order by
  s.time
